// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACh_CISQeYujxBGrKBzlgMq_AAiddTT1s',
    appId: '1:1037981369388:android:fff7e53c36ce68a4b6bd89',
    messagingSenderId: '1037981369388',
    projectId: 'course-49249',
    storageBucket: 'course-49249.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEqSpJSgW9-ATxMoPqa1JVFmqfnjTGuHU',
    appId: '1:1037981369388:ios:4db1928fe39d0f3cb6bd89',
    messagingSenderId: '1037981369388',
    projectId: 'course-49249',
    storageBucket: 'course-49249.appspot.com',
    iosBundleId: 'com.example.courseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBacFMpNiPNc-Pca5SJoMsYb1D5qr6ny5E',
    appId: '1:1037981369388:web:614e775ff8399531b6bd89',
    messagingSenderId: '1037981369388',
    projectId: 'course-49249',
    authDomain: 'course-49249.firebaseapp.com',
    storageBucket: 'course-49249.appspot.com',
    measurementId: 'G-BZJJND4JSB',
  );
}
